image: docker-proxy.myplayplanet.ch/maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s settings.xml --errors --fail-at-end --show-version -U -B"

cache:
  paths:
    - .m2/repository/
  key: "$CI_JOB_NAME"

stages:
  - deploy
  - trigger

build:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy -Dmaven.deploy.skip=true
  only:
    - merge_requests

deploy-snapshot:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - test
    - develop
    - development

deploy-release:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS build-helper:regex-property versions:set -N -Pci-release
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master
