image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/
  key: "$CI_PIPELINE_ID"
  untracked: true

stages:
  - build
  - deploy
  - trigger

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install
  only:
    - merge_requests

deploy-snapshot:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - test
    - develop
    - development

deploy-release:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy -P ci-release
  only:
    - master
