image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/
  key: "$CI_PIPELINE_ID"
  untracked: true

stages:
  - deploy

deploy-snapshot:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy -P ci-snapshot,deploy-snapshot,attach-javadocs,attach-sources
  only:
    - test
    - develop
    - development
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - target/*.jar

deploy-release:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy -P ci-release,deploy-release,attach-javadocs,attach-sources
  only:
    - master
  artifacts:
    when: on_success
    expire_in: 1 month
    paths:
      - target/*.jar
